THEN(
    THEN(
        INPUT_API.tag(
            "登录获取token"
        ).data(
            '{"nodeConfig":{"text":"登录获取token","remark":"","emptyDataProcessingEnabled":true,"createFileLog":true},"requestBodyConfig":{"id":"ClrBRubTOQ","authorization":{"authMethod":"No Auth","authorization":"","password":"","token":"","username":""},"preScript":"","postScript":"","body":{"contentType":"application/x-www-form-urlencoded","formParams":[{"id":"CppllwV5","desc":"","key":"username","value":"${UIAutoTestLoginUser}","isEdit":false},{"id":"EU53120R","desc":"","key":"password","value":"${UIAutoTestLoginPassword}","isEdit":false}],"formTemplate":"","showFormTemplate":""},"connectTimeout":30,"headers":[],"method":"POST","params":[],"readTimeout":300,"url":"${UIAutoTestBaseUrl}/prod-api/login","respBodyHandle":"$","previewType":"EXAMPLE_DATA","respDataExampleFlattening":[{"code":200,"msg":"登录成功","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInVzZXJfbmFtZSI6ImFkbWluIiwiZGVwdF9uYW1lIjoiXHU3ODE0XHU1M2QxXHU5MGU4XHU5NWU4Iiwic2Vzc2lvbl9pZCI6IjMwNWVjOWU3L6Mjc6NTIifSwiZXhwIjoxNzY0NjQyNDcyfQ.0s8hFc_cOu-ESB5md2FvNX4JQPfZF9jv3f_sHFw0CY8","success":true,"time":"2025-12-01T10:27:52.498861"}],"respPreviewParam":"ewogICJjb2RlIjogMjAwLAogICJtc2ciOiAi55m75b2V5oiQ5YqfIiwKICAidG9rZW4iOiAiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5WDJsa0lqb2lNU0lzSW5WelpYSmZibUZ0WlNJNkltRmtiV2x1SWl3aVpHVndkRjl1WVcxbElqb2lYSFUzT0RFMFhIVTFNMlF4WEhVNU1HVTRYSFU1TldVNElpd2ljMlZ6YzJsdmJsOXBaQ0k2SWpNd05XVmpPV1UzTFRGbE5tRXROR014WWkwNE5tVXhMVEEzWW1SbVpqWmlNalJqWmlJc0lteHZaMmx1WDJsdVptOGlPbnNpYVhCaFpHUnlJam9pTVRjeUxqRTJMamd1TVRZeUlpd2liRzluYVc1TWIyTmhkR2x2YmlJNklseDFOamN5WVZ4MU56ZGxOU0lzSW1KeWIzZHpaWElpT2lKQmNHRmphR1V0U0hSMGNFTnNhV1Z1ZENBMUlpd2liM01pT2lKUGRHaGxjaUlzSW14dloybHVWR2x0WlNJNklqSXdNalV0TVRJdE1ERWdNVEE2TWpjNk5USWlmU3dpWlhod0lqb3hOelkwTmpReU5EY3lmUS4wczhoRmNfY091LUVTQjVtZDJGdk5YNEpRUGZaRjlqdjNmX3NIRncwQ1k4IiwKICAic3VjY2VzcyI6IHRydWUsCiAgInRpbWUiOiAiMjAyNS0xMi0wMVQxMDoyNzo1Mi40OTg4NjEiCn0="},"responseBodyConfig":{"id":"beeb31dcaf85455b84960af11eb8b871","respCommonObjExtract":false,"respCustomObjExtract":true,"respCommonObjConfig":[],"respCustomObjObjConfig":[{"id":"F6pCfkM7","paramName":"authToken","paramValue":"$.token","isEdit":false}]}}'
        ),
        THEN(
            THEN(
                THEN(
                    SQL_SCRIPT.tag(
                        "SQL脚本-P94c"
                    ).data(
                        '{"nodeConfig":{"text":"SQL脚本-P94c","remark":"","emptyDataProcessingEnabled":true,"createFileLog":true},"sqlScriptConfig":{"sqlScript":"U0VMRUNUCgl0YXNrX2lkIApGUk9NCglhdXRvX2dlbmVyYXRlX3Rlc3RfcmVjb3JkcwpXSEVSRQoJdGFza190eXBlID0gMgoJQU5EIHRhc2tfc3RhdHVzID0gJ3BlbmRpbmcnIEFORCB0YXNrX2lkIGlzIG5vdCBudWxsOw==","dataSource":""}}'
                    )
                )
            ).tag(
                "_TAG_数据转换-获取执行中的任务"
            ),
            THEN(
                THEN(
                    ITERATOR(
                        PROCESS_ITERATOR.tag(
                            "循环容器-DYck"
                        ).data(
                            '{"nodeConfig":{"text":"循环容器-DYck","remark":"","emptyDataProcessingEnabled":true},"iteratorConfig":{"loopLimit":100,"loopType":"foreach","customScript":""}}'
                        )
                    ).DO(
                        THEN(
                            THEN(
                                INPUT_API.tag(
                                    "根据task_id查询任务结果"
                                ).data(
                                    '{"nodeConfig":{"text":"根据task_id查询任务结果","remark":"","emptyDataProcessingEnabled":false,"createFileLog":true},"requestBodyConfig":{"id":"arDvLEHN5q","authorization":{"authMethod":"Bearer Token","authorization":"","password":"","token":"${authToken}","username":""},"postScript":"","body":{"contentType":"application/json","formParams":[],"formTemplate":"e30=","showFormTemplate":"{}"},"connectTimeout":30,"headers":[{"id":"YWytazrb","desc":"","key":"Cookie","value":"Admin-Token=${authToken}","isEdit":false}],"method":"GET","params":[{"id":"q0nrAkZz","desc":"","key":"taskId","value":"${task_id}","isEdit":false}],"readTimeout":300,"url":"${UIAutoTestBaseUrl}/prod-api/record/record/list","respBodyHandle":"$.rows","previewType":"REAL_TIME","respDataExampleFlattening":[{"task_id":"62f0943c-22d4-4a9a-8d5d-64978ddcfd6d","workflow_run_id":"c53a29eb-b37c-47c9-bff0-db07bbd4f4ff","data":"{\\"id\\":\\"c53a29eb-b37c-47c9-bff0-db07bbd4f4ff\\",\\"workflow_id\\":\\"6f7f8311-0d6c-4ee0-b8d8-d3536d2db9a8\\",\\"status\\":\\"succeeded\\",\\"outputs\\":{\\"respones\\":\\"\\"},\\"error\\":\\"sdjasdjas\\",\\"elapsed_time\\":35.73181341961026,\\"total_tokens\\":2745,\\"total_steps\\":6,\\"created_at\\":1764227813,\\"finished_at\\":1764227849}","data.id":"c53a29eb-b37c-47c9-bff0-db07bbd4f4ff","data.workflow_id":"6f7f8311-0d6c-4ee0-b8d8-d3536d2db9a8","data.status":"succeeded","data.outputs":"{\\"respones\\":\\"\\"}","data.outputs.respones":"","data.error":"sdjasdjas","data.elapsed_time":35.73181341961026,"data.total_tokens":2745,"data.total_steps":6,"data.created_at":1764227813,"data.finished_at":1764227849}],"respPreviewParam":"ewogICJ0YXNrX2lkIjogIjYyZjA5NDNjLTIyZDQtNGE5YS04ZDVkLTY0OTc4ZGRjZmQ2ZCIsCiAgIndvcmtmbG93X3J1bl9pZCI6ICJjNTNhMjllYi1iMzdjLTQ3YzktYmZmMC1kYjA3YmJkNGY0ZmYiLAogICJkYXRhIjogewogICAgImlkIjogImM1M2EyOWViLWIzN2MtNDdjOS1iZmYwLWRiMDdiYmQ0ZjRmZiIsCiAgICAid29ya2Zsb3dfaWQiOiAiNmY3ZjgzMTEtMGQ2Yy00ZWUwLWI4ZDgtZDM1MzZkMmRiOWE4IiwKICAgICJzdGF0dXMiOiAic3VjY2VlZGVkIiwKICAgICJvdXRwdXRzIjogewogICAgICAicmVzcG9uZXMiOiX3Rva2VLAogICAgImNyZWF0ZWRfYXQiOiAxNzY0MjI3ODEzLAogICAgImZpbmlzaGVkX2F0IjogMTc2NDIyNzg0OQogIH0KfQ=="},"responseBodyConfig":{"id":"fd85bb782adb4a5181c040333b522c13","respCommonObjExtract":false,"respCustomObjExtract":true,"respCommonObjConfig":[],"respCustomObjObjConfig":[{"id":"15GWqHHF","paramName":"apiResponseTaskTotal","paramValue":"$.total","isEdit":false},{"id":"0bMginei","paramName":"apiResponseTaskStatus","paramValue":"$.rows[0].status","isEdit":false}]}}'
                                ),
                                THEN(
                                    SWITCH(
                                        CONDITIONAL_BRANCH.tag(
                                            "根据查询的结果做分支"
                                        ).data(
                                            '{"nodeConfig":{"text":"根据查询的结果做分支","remark":"","emptyDataProcessingEnabled":true,"createFileLog":true},"branchConfig":{"tableData":[{"id":"l9MUqXEO7j","nextNode":"根据实际返回的状态做数据分发","condition":"${apiResponseTaskTotal}==1","remark":""},{"id":"ijMWNFWLO2","nextNode":"查询回来的数据为0","condition":"${apiResponseTaskTotal}!=1","remark":""}]}}'
                                        )
                                    ).TO(
                                        THEN(
                                            THEN(
                                                THEN(
                                                    FIELD_MAPPING.tag(
                                                        "字段映射-Ouow"
                                                    ).data(
                                                        '{"nodeConfig":{"text":"字段映射-Ouow","remark":"","emptyDataProcessingEnabled":false},"fieldMappingConfig":{"tableData":[{"id":"arsSuAIPHH","sourceField":"task_id","targetField":"task_id"},{"id":"ubrbmHOvOC","sourceField":"fail","targetField":"task_status"}],"tableName":""}}'
                                                    ),
                                                    THEN(
                                                        OUTPUT_DB.tag(
                                                            "DB表输出-jSvh"
                                                        ).data(
                                                            '{"nodeConfig":{"text":"DB表输出-jSvh","remark":"","emptyDataProcessingEnabled":false},"dataOutputConfig":{"tableName":"AUTO_GENERATE_TEST_RECORDS","dbWrite":"1","logoFields":["task_id"],"primaryKeyMapping":"","batchNum":2000,"physicalDelete":false}}'
                                                        )
                                                    )
                                                )
                                            ).tag(
                                                "___TAG_查询回来的数据为0"
                                            )
                                        ).tag(
                                            "_TAG_查询回来的数据为0"
                                        ),
                                        THEN(
                                            SWITCH(
                                                CONDITIONAL_BRANCH.tag(
                                                    "根据实际返回的状态做数据分发"
                                                ).data(
                                                    '{"nodeConfig":{"text":"根据实际返回的状态做数据分发","remark":"","emptyDataProcessingEnabled":true,"createFileLog":true},"branchConfig":{"tableData":[{"id":"d6Mm9vsvEV","nextNode":"成功","condition":"${apiResponseTaskStatus}==\\'success\\'","remark":""},{"id":"JXnRzFNYBC","nextNode":"失败","condition":"${apiResponseTaskStatus}==\\'fail\\'","remark":""},{"id":"2VUrUAmLMV","nextNode":"排队中","condition":"${apiResponseTaskStatus}==\\'queue\\'","remark":""},{"id":"jFxfJI8k3b","nextNode":"执行中","condition":"${apiResponseTaskStatus}==\\'pending\\'","remark":""},{"id":"hzWRomkcPp","nextNode":"异常","condition":"${apiResponseTaskStatus}==\\'error\\'","remark":""}]}}'
                                                )
                                            ).TO(
                                                THEN(
                                                    THEN(
                                                        THEN(
                                                            FIELD_MAPPING.tag(
                                                                "排队中入记录表"
                                                            ).data(
                                                                '{"nodeConfig":{"text":"排队中入记录表","remark":"","emptyDataProcessingEnabled":false},"fieldMappingConfig":{"tableData":[{"id":"z2wh3oNGT2","sourceField":"task_id","targetField":"task_id"},{"id":"ElIUphfcOs","sourceField":"pending","targetField":"task_status"}],"tableName":""}}'
                                                            ),
                                                            THEN(
                                                                OUTPUT_DB.tag(
                                                                    "记录表-Q"
                                                                ).data(
                                                                    '{"nodeConfig":{"text":"记录表-Q","remark":"","emptyDataProcessingEnabled":false},"dataOutputConfig":{"tableName":"AUTO_GENERATE_TEST_RECORDS","dbWrite":"1","logoFields":["task_id"],"primaryKeyMapping":"","batchNum":2000,"physicalDelete":false}}'
                                                                )
                                                            )
                                                        )
                                                    ).tag(
                                                        "___TAG_排队中"
                                                    )
                                                ).tag(
                                                    "_TAG_排队中"
                                                ),
                                                THEN(
                                                    THEN(
                                                        THEN(
                                                            FIELD_MAPPING.tag(
                                                                "执行中入记录表"
                                                            ).data(
                                                                '{"nodeConfig":{"text":"执行中入记录表","remark":"","emptyDataProcessingEnabled":false},"fieldMappingConfig":{"tableData":[{"id":"zE0UTSMZWq","sourceField":"task_id","targetField":"task_id"},{"id":"CLuksy2YuL","sourceField":"pending","targetField":"task_status"}],"tableName":""}}'
                                                            ),
                                                            THEN(
                                                                OUTPUT_DB.tag(
                                                                    "记录表B"
                                                                ).data(
                                                                    '{"nodeConfig":{"text":"记录表B","remark":"","emptyDataProcessingEnabled":false},"dataOutputConfig":{"tableName":"AUTO_GENERATE_TEST_RECORDS","dbWrite":"1","logoFields":["task_id"],"primaryKeyMapping":"","batchNum":2000,"physicalDelete":false}}'
                                                                )
                                                            )
                                                        )
                                                    ).tag(
                                                        "___TAG_执行中"
                                                    )
                                                ).tag(
                                                    "_TAG_执行中"
                                                ),
                                                THEN(
                                                    THEN(
                                                        THEN(
                                                            FIELD_MAPPING.tag(
                                                                "成功入记录表"
                                                            ).data(
                                                                '{"nodeConfig":{"text":"成功入记录表","remark":"","emptyDataProcessingEnabled":false},"fieldMappingConfig":{"tableData":[{"id":"VcOo6hFDs4","sourceField":"task_id","targetField":"task_id"},{"id":"xLihdgufqU","sourceField":"success","targetField":"task_status"},{"id":"OB5W5RthJO","sourceField":"reportUrl","targetField":"task_result_url"}],"tableName":""}}'
                                                            ),
                                                            THEN(
                                                                OUTPUT_DB.tag(
                                                                    "记录表C"
                                                                ).data(
                                                                    '{"nodeConfig":{"text":"记录表C","remark":"","emptyDataProcessingEnabled":false},"dataOutputConfig":{"tableName":"AUTO_GENERATE_TEST_RECORDS","dbWrite":"1","logoFields":["task_id"],"primaryKeyMapping":"","batchNum":2000,"physicalDelete":false}}'
                                                                )
                                                            )
                                                        )
                                                    ).tag(
                                                        "___TAG_成功"
                                                    )
                                                ).tag(
                                                    "_TAG_成功"
                                                ),
                                                THEN(
                                                    THEN(
                                                        THEN(
                                                            FIELD_MAPPING.tag(
                                                                "失败入记录表"
                                                            ).data(
                                                                '{"nodeConfig":{"text":"失败入记录表","remark":"","emptyDataProcessingEnabled":false,"createFileLog":true},"fieldMappingConfig":{"tableData":[{"id":"Z5AkzWV043","sourceField":"task_id","targetField":"task_id"},{"id":"p8zOMHNbAx","sourceField":"success","targetField":"task_status"},{"id":"PiJ77X4x2I","sourceField":"reportUrl","targetField":"task_result_url"}],"tableName":""}}'
                                                            ),
                                                            THEN(
                                                                OUTPUT_DB.tag(
                                                                    "记录表D"
                                                                ).data(
                                                                    '{"nodeConfig":{"text":"记录表D","remark":"","emptyDataProcessingEnabled":false},"dataOutputConfig":{"tableName":"AUTO_GENERATE_TEST_RECORDS","dbWrite":"1","logoFields":["task_id"],"primaryKeyMapping":"","batchNum":2000,"physicalDelete":false}}'
                                                                )
                                                            )
                                                        )
                                                    ).tag(
                                                        "___TAG_失败"
                                                    )
                                                ).tag(
                                                    "_TAG_失败"
                                                ),
                                                THEN(
                                                    THEN(
                                                        THEN(
                                                            FIELD_MAPPING.tag(
                                                                "异常入记录表"
                                                            ).data(
                                                                '{"nodeConfig":{"text":"异常入记录表","remark":"","emptyDataProcessingEnabled":false},"fieldMappingConfig":{"tableData":[{"id":"MqDSTC1NuC","sourceField":"task_id","targetField":"task_id"},{"id":"tMcGpbPffO","sourceField":"error","targetField":"task_status"},{"id":"tLYPuDDzAi","sourceField":"errorInfo","targetField":"error_info"}],"tableName":""}}'
                                                            ),
                                                            THEN(
                                                                OUTPUT_DB.tag(
                                                                    "记录表E"
                                                                ).data(
                                                                    '{"nodeConfig":{"text":"记录表E","remark":"","emptyDataProcessingEnabled":false},"dataOutputConfig":{"tableName":"AUTO_GENERATE_TEST_RECORDS","dbWrite":"1","logoFields":["task_id"],"primaryKeyMapping":"","batchNum":2000,"physicalDelete":false}}'
                                                                )
                                                            )
                                                        )
                                                    ).tag(
                                                        "___TAG_异常"
                                                    )
                                                ).tag(
                                                    "_TAG_异常"
                                                )
                                            )
                                        ).tag(
                                            "_TAG_根据实际返回的状态做数据分发"
                                        )
                                    )
                                )
                            )
                        )
                    )
                ).tag(
                    "_TAG_循环容器-DYck"
                )
            )
        )
    )
)